<?php

namespace Database\Seeders;

use App\Models\Circular;
use App\Models\Employer;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CircularSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Real job data array
        $jobs = [
            [
                'employer_id' => 1,
                'category_id' => 1,
                'company_id' => 1,
                'title' => 'Senior Software Engineer',
                'description' => 'We are looking for a highly skilled Senior Software Engineer to join our team.',
                'current_company_name' => 'ABC Tech Solutions',
                'location' => 'San Francisco',
                'location_type' => 'office',
                'vacancies' => 3,
                'employment_type' => 'full-time',
                'salary' => 120000,
                'experience_level' => 'senior-level',
                'deadline' => '2024-06-30',
                'is_remote' => 0,
            ],
            [
                'employer_id' => 2,
                'category_id' => 2,
                'company_id' => 2,
                'title' => 'Web Developer',
                'description' => 'We are seeking a talented Web Developer to join our dynamic team.',
                'current_company_name' => 'XYZ Web Solutions',
                'location' => 'New York',
                'location_type' => 'office',
                'vacancies' => 2,
                'employment_type' => 'full-time',
                'salary' => 90000,
                'experience_level' => 'mid-level',
                'deadline' => '2024-07-15',
                'is_remote' => 0,
            ],
            [
                'employer_id' => 3,
                'category_id' => 3,
                'company_id' => 3,
                'title' => 'Data Scientist',
                'description' => 'We are looking for a talented Data Scientist to join our analytics team.',
                'current_company_name' => 'Data Insights Inc.',
                'location' => 'Seattle',
                'location_type' => 'office',
                'vacancies' => 1,
                'employment_type' => 'full-time',
                'salary' => 140000,
                'experience_level' => 'senior-level',
                'deadline' => '2024-07-30',
                'is_remote' => 0,
            ],
            [
                'employer_id' => 4,
                'category_id' => 4,
                'company_id' => 4,
                'title' => 'UX/UI Designer',
                'description' => 'We are seeking a creative and talented UX/UI Designer to join our design team.',
                'current_company_name' => 'Creative Design Agency',
                'location' => 'Los Angeles',
                'location_type' => 'office',
                'vacancies' => 2,
                'employment_type' => 'full-time',
                'salary' => 100000,
                'experience_level' => 'mid-level',
                'deadline' => '2024-08-15',
                'is_remote' => 0,
            ],
            [
                'employer_id' => 5,
                'category_id' => 5,
                'company_id' => 5,
                'title' => 'Marketing Manager',
                'description' => 'We are looking for an experienced Marketing Manager to lead our marketing initiatives.',
                'current_company_name' => 'Global Marketing Solutions',
                'location' => 'London',
                'location_type' => 'office',
                'vacancies' => 1,
                'employment_type' => 'full-time',
                'salary' => 110000,
                'experience_level' => 'senior-level',
                'deadline' => '2024-09-01',
                'is_remote' => 0,
            ],
            [
                'employer_id' => 6,
                'category_id' => 6,
                'company_id' => 6,
                'title' => 'Financial Analyst',
                'description' => 'We are seeking a skilled Financial Analyst to join our finance team.',
                'current_company_name' => 'Capital Investments Ltd.',
                'location' => 'Toronto',
                'location_type' => 'office',
                'vacancies' => 2,
                'employment_type' => 'full-time',
                'salary' => 95000,
                'experience_level' => 'mid-level',
                'deadline' => '2024-08-30',
                'is_remote' => 0,
            ],
            [
                'employer_id' => 7,
                'category_id' => 7,
                'company_id' => 7,
                'title' => 'Software Developer',
                'description' => 'We are looking for a Software Developer to join our development team.',
                'current_company_name' => 'Tech Solutions Bangladesh',
                'location' => 'Dhaka',
                'location_type' => 'office',
                'vacancies' => 3,
                'employment_type' => 'full-time',
                'salary' => 80000,
                'experience_level' => 'entry-level',
                'deadline' => '2024-09-15',
                'is_remote' => 0,
            ],
            [
                'employer_id' => 8,
                'category_id' => 8,
                'company_id' => 8,
                'title' => 'Graphic Designer',
                'description' => 'We are seeking a talented Graphic Designer to join our creative team.',
                'current_company_name' => 'Creative Minds Bangladesh',
                'location' => 'Chittagong',
                'location_type' => 'office',
                'vacancies' => 2,
                'employment_type' => 'full-time',
                'salary' => 70000,
                'experience_level' => 'mid-level',
                'deadline' => '2024-09-10',
                'is_remote' => 0,
            ],
            [
                'employer_id' => 9,
                'category_id' => 9,
                'company_id' => 9,
                'title' => 'HR Manager',
                'description' => 'We are looking for an experienced HR Manager to oversee our human resources department.',
                'current_company_name' => 'HR Solutions Bangladesh',
                'location' => 'Sylhet',
                'location_type' => 'office',
                'vacancies' => 1,
                'employment_type' => 'full-time',
                'salary' => 100000,
                'experience_level' => 'senior-level',
                'deadline' => '2024-09-20',
                'is_remote' => 0,
            ],
            [
                'employer_id' => 10,
                'category_id' => 10,
                'company_id' => 10,
                'title' => 'Sales Executive',
                'description' => 'We are seeking a Sales Executive to join our sales team.',
                'current_company_name' => 'Sales Solutions Bangladesh',
                'location' => 'Khulna',
                'location_type' => 'office',
                'vacancies' => 2,
                'employment_type' => 'full-time',
                'salary' => 90000,
                'experience_level' => 'mid-level',
                'deadline' => '2024-09-25',
                'is_remote' => 0,
            ],
            [
                'employer_id' => 11,
                'category_id' => 11,
                'company_id' => 11,
                'title' => 'Accountant',
                'description' => 'We are looking for a skilled Accountant to manage our financial records.',
                'current_company_name' => 'Finance Solutions Bangladesh',
                'location' => 'Rajshahi',
                'location_type' => 'office',
                'vacancies' => 1,
                'employment_type' => 'full-time',
                'salary' => 85000,
                'experience_level' => 'mid-level',
                'deadline' => '2024-10-01',
                'is_remote' => 0,
            ],
            [
                'employer_id' => 12,
                'category_id' => 12,
                'company_id' => 12,
                'title' => 'Content Writer',
                'description' => 'We are seeking a talented Content Writer to create engaging content for our digital platforms.',
                'current_company_name' => 'Content Creators Bangladesh',
                'location' => 'Barisal',
                'location_type' => 'office',
                'vacancies' => 2,
                'employment_type' => 'full-time',
                'salary' => 75000,
                'experience_level' => 'entry-level',
                'deadline' => '2024-10-05',
                'is_remote' => 0,
            ],
            [
                'employer_id' => 13,
                'category_id' => 13,
                'company_id' => 13,
                'title' => 'Customer Service Representative',
                'description' => 'We are looking for a Customer Service Representative to assist our clients with their inquiries.',
                'current_company_name' => 'Customer Care Solutions Bangladesh',
                'location' => 'Dinajpur',
                'location_type' => 'office',
                'vacancies' => 1,
                'employment_type' => 'full-time',
                'salary' => 70000,
                'experience_level' => 'entry-level',
                'deadline' => '2024-10-10',
                'is_remote' => 0,
            ],
            [
                'employer_id' => 14,
                'category_id' => 14,
                'company_id' => 14,
                'title' => 'Project Manager',
                'description' => 'We are seeking an experienced Project Manager to oversee our project initiatives.',
                'current_company_name' => 'Project Management Solutions Bangladesh',
                'location' => 'Comilla',
                'location_type' => 'office',
                'vacancies' => 1,
                'employment_type' => 'full-time',
                'salary' => 110000,
                'experience_level' => 'senior-level',
                'deadline' => '2024-10-15',
                'is_remote' => 0,
            ],
            [
                'employer_id' => 15,
                'category_id' => 15,
                'company_id' => 15,
                'title' => 'Software Engineer',
                'description' => 'We are looking for a skilled Software Engineer to develop and maintain our software systems.',
                'current_company_name' => 'Software Solutions Bangladesh',
                'location' => 'Jessore',
                'location_type' => 'office',
                'vacancies' => 2,
                'employment_type' => 'full-time',
                'salary' => 90000,
                'experience_level' => 'mid-level',
                'deadline' => '2024-10-20',
                'is_remote' => 0,
            ],
            [
                'employer_id' => 16,
                'category_id' => 16,
                'company_id' => 16,
                'title' => 'Digital Marketing Specialist',
                'description' => 'We are seeking a Digital Marketing Specialist to develop and execute our digital marketing strategies.',
                'current_company_name' => 'Digital Marketing Solutions Bangladesh',
                'location' => 'Narayanganj',
                'location_type' => 'office',
                'vacancies' => 1,
                'employment_type' => 'full-time',
                'salary' => 95000,
                'experience_level' => 'mid-level',
                'deadline' => '2024-10-25',
                'is_remote' => 0,
            ],
            [
                'employer_id' => 17,
                'category_id' => 17,
                'company_id' => 17,
                'title' => 'Human Resources Assistant',
                'description' => 'We are seeking a Human Resources Assistant to provide administrative support to our HR department.',
                'current_company_name' => 'HR Solutions Bangladesh',
                'location' => 'Rangpur',
                'location_type' => 'office',
                'vacancies' => 1,
                'employment_type' => 'full-time',
                'salary' => 70000,
                'experience_level' => 'entry-level',
                'deadline' => '2024-10-30',
                'is_remote' => 0,
            ],
            [
                'employer_id' => 18,
                'category_id' => 18,
                'company_id' => 18,
                'title' => 'Sales Manager',
                'description' => 'We are seeking an experienced Sales Manager to lead our sales team.',
                'current_company_name' => 'Sales Solutions Bangladesh',
                'location' => 'Bogra',
                'location_type' => 'office',
                'vacancies' => 1,
                'employment_type' => 'full-time',
                'salary' => 120000,
                'experience_level' => 'senior-level',
                'deadline' => '2024-11-01',
                'is_remote' => 0,
            ],
            [
                'employer_id' => 19,
                'category_id' => 19,
                'company_id' => 19,
                'title' => 'Customer Support Specialist',
                'description' => 'We are seeking a Customer Support Specialist to assist our customers with their inquiries and issues.',
                'current_company_name' => 'Customer Care Solutions Bangladesh',
                'location' => 'Cox\'s Bazar',
                'location_type' => 'office',
                'vacancies' => 2,
                'employment_type' => 'full-time',
                'salary' => 75000,
                'experience_level' => 'mid-level',
                'deadline' => '2024-11-05',
                'is_remote' => 0,
            ],
            [
                'employer_id' => 20,
                'category_id' => 20,
                'company_id' => 20,
                'title' => 'Web Developer',
                'description' => 'We are looking for a Web Developer to design and develop our company\'s website.',
                'current_company_name' => 'Web Solutions Bangladesh',
                'location' => 'Sylhet',
                'location_type' => 'office',
                'vacancies' => 1,
                'employment_type' => 'full-time',
                'salary' => 85000,
                'experience_level' => 'mid-level',
                'deadline' => '2024-11-10',
                'is_remote' => 0,
            ],
            [
                'employer_id' => 21,
                'category_id' => 21,
                'company_id' => 21,
                'title' => 'Finance Manager',
                'description' => 'We are seeking a Finance Manager to oversee our financial operations and reporting.',
                'current_company_name' => 'Finance Solutions Bangladesh',
                'location' => 'Rajshahi',
                'location_type' => 'office',
                'vacancies' => 1,
                'employment_type' => 'full-time',
                'salary' => 110000,
                'experience_level' => 'senior-level',
                'deadline' => '2024-11-15',
                'is_remote' => 0,
            ],
            [
                'employer_id' => 22,
                'category_id' => 22,
                'company_id' => 22,
                'title' => 'Marketing Manager',
                'description' => 'We are seeking a Marketing Manager to develop and implement our marketing strategies.',
                'current_company_name' => 'Marketing Solutions Bangladesh',
                'location' => 'Dhaka',
                'location_type' => 'office',
                'vacancies' => 1,
                'employment_type' => 'full-time',
                'salary' => 100000,
                'experience_level' => 'senior-level',
                'deadline' => '2024-11-20',
                'is_remote' => 0,
            ],
            [
                'employer_id' => 23,
                'category_id' => 23,
                'company_id' => 23,
                'title' => 'Graphic Designer',
                'description' => 'We are looking for a creative Graphic Designer to develop visual concepts for our brand.',
                'current_company_name' => 'Design Solutions Bangladesh',
                'location' => 'Khulna',
                'location_type' => 'office',
                'vacancies' => 1,
                'employment_type' => 'full-time',
                'salary' => 90000,
                'experience_level' => 'mid-level',
                'deadline' => '2024-11-25',
                'is_remote' => 0,
            ],
            [
                'employer_id' => 24,
                'category_id' => 24,
                'company_id' => 24,
                'title' => 'Quality Assurance Analyst',
                'description' => 'We are seeking a detail-oriented Quality Assurance Analyst to ensure the quality of our software products.',
                'current_company_name' => 'QA Solutions Bangladesh',
                'location' => 'Narayanganj',
                'location_type' => 'office',
                'vacancies' => 1,
                'employment_type' => 'full-time',
                'salary' => 95000,
                'experience_level' => 'mid-level',
                'deadline' => '2024-11-30',
                'is_remote' => 0,
            ],
            [
                'employer_id' => 25,
                'category_id' => 25,
                'company_id' => 25,
                'title' => 'Operations Manager',
                'description' => 'We are seeking an Operations Manager to oversee our day-to-day operations.',
                'current_company_name' => 'Operations Solutions Bangladesh',
                'location' => 'Chittagong',
                'location_type' => 'office',
                'vacancies' => 1,
                'employment_type' => 'full-time',
                'salary' => 100000,
                'experience_level' => 'senior-level',
                'deadline' => '2024-12-05',
                'is_remote' => 0,
            ],
            [
                'employer_id' => 26,
                'category_id' => 26,
                'company_id' => 26,
                'title' => 'IT Support Specialist',
                'description' => 'We are seeking an IT Support Specialist to provide technical assistance to our employees.',
                'current_company_name' => 'IT Solutions Bangladesh',
                'location' => 'Mymensingh',
                'location_type' => 'office',
                'vacancies' => 1,
                'employment_type' => 'full-time',
                'salary' => 85000,
                'experience_level' => 'mid-level',
                'deadline' => '2024-12-10',
                'is_remote' => 0,
            ],
            [
                'employer_id' => 27,
                'category_id' => 27,
                'company_id' => 27,
                'title' => 'Legal Assistant',
                'description' => 'We are seeking a Legal Assistant to provide support to our legal team.',
                'current_company_name' => 'Legal Solutions Bangladesh',
                'location' => 'Rangpur',
                'location_type' => 'office',
                'vacancies' => 1,
                'employment_type' => 'full-time',
                'salary' => 70000,
                'experience_level' => 'entry-level',
                'deadline' => '2024-12-15',
                'is_remote' => 0,
            ],
            [
                'employer_id' => 28,
                'category_id' => 28,
                'company_id' => 28,
                'title' => 'Healthcare Assistant',
                'description' => 'We are seeking a Healthcare Assistant to provide care and support to our patients.',
                'current_company_name' => 'Healthcare Solutions Bangladesh',
                'location' => 'Barisal',
                'location_type' => 'office',
                'vacancies' => 1,
                'employment_type' => 'full-time',
                'salary' => 75000,
                'experience_level' => 'entry-level',
                'deadline' => '2024-12-20',
                'is_remote' => 0,
            ],
            [
                'employer_id' => 29,
                'category_id' => 29,
                'company_id' => 29,
                'title' => 'Education Coordinator',
                'description' => 'We are seeking an Education Coordinator to manage our educational programs.',
                'current_company_name' => 'Education Solutions Bangladesh',
                'location' => 'Comilla',
                'location_type' => 'office',
                'vacancies' => 1,
                'employment_type' => 'full-time',
                'salary' => 80000,
                'experience_level' => 'entry-level',
                'deadline' => '2024-12-25',
                'is_remote' => 0,
            ],

            // Add more job entries as needed
        ];
        foreach ($jobs as $item) {
            $employer = Employer::inRandomOrder()->first();
            $item['company_id'] = $employer->company_id;
            $item['employer_id'] = $employer->id;
            Circular::create($item);
        }
    }
}
