services:

  jumpintojob:
    container_name: jumpintojob
    build: .
    volumes:
      - ./:/var/www/html
    ports:
      - 8090:80
    restart: unless-stopped
  
  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: app
      MYSQL_DATABASE: jumpinto_db
    ports:
    - 3308:3306
    restart: unless-stopped
  
  # phpmyadmin:
  #   image: phpmyadmin:latest
  #   ports:
  #     - 9001:80
  #   environment:
  #     - PMA_ARBITRARY=1