services:
  backend:
    build:
      context: ./bin/docker/php
    volumes:
      - .:/app
    ports:
      - "9003:9003" #xdebug port
    working_dir: /app
    image: laravel/app

  queue:
    depends_on:
     - backend
     - mariadb
     - nginx
    image: laravel/app
    command: php artisan queue:work --sleep=3 --tries=3   --timeout=120
    working_dir: /app
    volumes:
      - .:/app
    restart: unless-stopped

  mariadb:
    image: mariadb:10.5.7
    depends_on:
      - backend
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=app
      - MYSQL_USER=root
      - MYSQL_PASSWORD=app
      - MYSQL_DATABASE=jumpinto_db
    restart: unless-stopped

  nginx:
    build:
      context: ./bin/docker/nginx
    ports:
      - "8090:80"
    depends_on:
      - backend
    volumes:
      - .:/app
    restart: unless-stopped
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 9001:80
    depends_on:
      - mariadb
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=app
    restart: unless-stopped
    
networks:
  default:
    name: backend-network

