services:
    backend:
        build:
            context: ./bin/docker/php
        volumes:
            - .:/app
        ports:
            - "9003:9003" # xdebug port
        working_dir: /app
        image: laravel/app
        restart: unless-stopped
        depends_on:
            - mariadb
            - mongodb

    queue:
        image: laravel/app
        working_dir: /app
        volumes:
            - .:/app
        restart: unless-stopped
        depends_on:
            - backend
            - mariadb
            - mongodb
            - nginx

    mariadb:
        image: mariadb:10.5.7
        ports:
            - "3308:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=app
            - MYSQL_USER=root
            - MYSQL_PASSWORD=app
            - MYSQL_DATABASE=jumpinto_db
        restart: unless-stopped

    nginx:
        build:
            context: ./bin/docker/nginx
        ports:
            - "80:80"
            - "443:80"
        volumes:
            - .:/app
            - ./storage:/app/storage:delegated
        restart: unless-stopped
        depends_on:
            - backend

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - "9001:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mariadb
            - PMA_USER=root
            - PMA_PASSWORD=app
        restart: unless-stopped
        depends_on:
            - mariadb

    mongodb:
        image: mongo:latest
        ports:
            - "27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=example
        volumes:
            - mongodb-data:/data/db
        restart: unless-stopped

    mongo-express:
        image: mongo-express:latest
        ports:
            - "8081:8081"
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=example
            - ME_CONFIG_MONGODB_SERVER=mongodb
        restart: unless-stopped
        depends_on:
            - mongodb

    htmltoimage:
        image: "monkeyphysics/html-to-image"
        ports:
            - "3033:3033"
        restart: unless-stopped

volumes:
    mongodb-data:

networks:
    default:
        name: backend-network
