services:

  jumpintojob:
    container_name: backend
    build: .
    volumes:
      - ./:/var/www/html
    ports:
      - 8090:80
    restart: unless-stopped

  db:
    image: mariadb:10.5.7
    ports:
      - '3308:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=app
      - MYSQL_USER=root
      - MYSQL_PASSWORD=app
      - MYSQL_DATABASE=jumpinto_db
    restart: unless-stopped

  # phpmyadmin:
  #   image: phpmyadmin:latest
  #   ports:
  #     - 9001:80
  #   environment:
  #     - PMA_ARBITRARY=1
