services:

  jumpintojob:
    container_name: jumpintojob
    build: .
    volumes:
      - ./:/var/www/html:consistent
    ports:
      - 8090:80
    restart: unless-stopped
  
  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: app
      MYSQL_DATABASE: jumpinto_db
    ports:
      - 3308:3306
    restart: unless-stopped
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql_db
      - PMA_USER=root
      - PMA_PASSWORD=app
    restart: unless-stopped
