version: '3'

services:
  app:
    depends_on:
      - db
  nginx:
    image: 'bitnami/nginx:latest'
    depends_on:
      - app
    ports:
      - '80:80'
    volumes:
      - ./bin/nginx.server.block.dev.conf:/opt/bitnami/nginx/conf/server_blocks/ap.conf
      - ./public/resource:/app
  db:
    image: mariadb:10.5.7
    ports:
      - '3308:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
      - MYSQL_DATABASE=new_backoffice